"POST /sg/api/login HTTP/1.1" 200 92
"GET /sg/swasthgarbh/patient/1 HTTP/1.1" 200 4297
INFO 2019-01-29 12:53:53,792 basehttp 30656 140231907727104 "POST /sg/api/login HTTP/1.1" 200 92
INFO 2019-01-29 13:00:49,091 basehttp 30839 139674915272448 "POST /sg/api/login HTTP/1.1" 200 92
INFO 2019-01-29 13:01:43,026 basehttp "POST /sg/api/login HTTP/1.1" 200 92
INFO 2019-01-29 14:18:05,922 basehttp "POST /sg/api/login HTTP/1.1" 200 92
- - "- - -" - Internal Server Error: /sg/api/login 2019-01-29 14:27:08,774
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'LogSetupMiddleware' object is not callable
- - "- - -" - "POST /sg/api/login HTTP/1.1" 500 55441 2019-01-29 14:27:08,775
- - "- - -" - Internal Server Error: /sg/api/login 2019-01-29 14:27:30,734
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'LogSetupMiddleware' object is not callable
- - "- - -" - "POST /sg/api/login HTTP/1.1" 500 55441 2019-01-29 14:27:30,735
- - "- - -" - Internal Server Error: /sg/api/login 2019-01-29 14:29:06,131
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'LogSetupMiddleware' object is not callable
- - "- - -" - "POST /sg/api/login HTTP/1.1" 500 55441 2019-01-29 14:29:06,131
- - "- - -" - Internal Server Error: /sg/api/login 2019-01-29 14:29:55,073
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'LogSetupMiddleware' object is not callable
- - "- - -" - "POST /sg/api/login HTTP/1.1" 500 55441 2019-01-29 14:29:55,073
- - "- - -" - Internal Server Error: /sg/cbtbiitr/api/device 2019-01-29 14:32:30,548
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'LogSetupMiddleware' object is not callable
- - "- - -" - "POST /sg/cbtbiitr/api/device HTTP/1.1" 500 54295 2019-01-29 14:32:30,549
- - "- - -" - Internal Server Error: /sg//api/login 2019-01-29 14:32:37,690
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'LogSetupMiddleware' object is not callable
- - "- - -" - "POST /sg//api/login HTTP/1.1" 500 54222 2019-01-29 14:32:37,691
INFO 2019-01-29 14:33:15,021 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 14:33:17,170 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 14:33:17,263 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 11675
INFO 2019-01-29 14:33:17,431 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:41:38,071 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
WARNING 2019-01-29 15:41:38,131 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 15:41:38,132 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 15:41:38,147 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 15:41:38,148 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 15:41:43,031 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 15:41:43,032 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 15:41:43,082 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 15:41:43,082 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 15:41:50,295 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 15:41:52,432 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 15:41:52,480 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 11675
INFO 2019-01-29 15:41:52,640 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:41:55,287 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 367
INFO 2019-01-29 15:41:57,285 basehttp "GET /sg/api/singleimage/4 HTTP/1.1" 200 202508
INFO 2019-01-29 15:42:10,537 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 11675
INFO 2019-01-29 15:42:10,871 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:42:19,275 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 11675
INFO 2019-01-29 15:42:19,410 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:42:23,747 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 367
INFO 2019-01-29 15:43:01,127 basehttp "POST /sg//api/image HTTP/1.1" 201 5956
INFO 2019-01-29 15:43:01,189 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 11750
INFO 2019-01-29 15:43:01,456 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:43:01,913 basehttp "POST /sg/api/data HTTP/1.1" 201 328
INFO 2019-01-29 15:43:13,046 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12109
INFO 2019-01-29 15:43:13,172 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:43:17,095 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12109
INFO 2019-01-29 15:43:17,230 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:43:20,568 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
INFO 2019-01-29 15:43:22,594 basehttp "GET /sg/api/singleimage/5 HTTP/1.1" 200 5949
INFO 2019-01-29 15:43:35,392 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 15:43:35,473 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12109
INFO 2019-01-29 15:43:35,807 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:43:38,629 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
INFO 2019-01-29 15:45:36,701 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 15:45:36,787 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12109
INFO 2019-01-29 15:45:37,088 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 15:45:40,325 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
ERROR 2019-01-29 15:45:43,271 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 15:45:43,272 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17816
ERROR 2019-01-29 15:45:56,483 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 15:45:56,484 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17816
INFO 2019-01-29 15:46:00,158 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
INFO 2019-01-29 15:46:01,777 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
INFO 2019-01-29 15:54:57,329 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
INFO 2019-01-29 15:54:58,273 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
ERROR 2019-01-29 15:56:29,898 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 15:56:29,899 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17816
INFO 2019-01-29 15:57:10,011 basehttp "POST /sg/api/login HTTP/1.1" 200 92
INFO 2019-01-29 15:57:56,101 basehttp "GET /sg/api/singleimage/5 HTTP/1.1" 200 5949
ERROR 2019-01-29 15:58:16,720 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 15:58:16,720 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 18071
ERROR 2019-01-29 16:02:26,403 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 412, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-01-29 16:02:26,404 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 83979
ERROR 2019-01-29 16:02:44,433 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 76, in delete
    query = Image.objects.get(id=pk)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
cvd_portal.models.Image.DoesNotExist: Image matching query does not exist.
ERROR 2019-01-29 16:02:44,434 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17750
WARNING 2019-01-29 16:05:23,897 log Unauthorized: /sg/api/singleimage/5
WARNING 2019-01-29 16:05:23,897 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 401 27
WARNING 2019-01-29 16:05:23,944 log Unauthorized: /sg/api/singleimage/5
WARNING 2019-01-29 16:05:23,945 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 401 27
ERROR 2019-01-29 16:07:35,898 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: delete() got multiple values for argument 'pk'
ERROR 2019-01-29 16:07:35,899 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17301
ERROR 2019-01-29 16:08:25,720 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 412, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-01-29 16:08:25,721 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 83979
ERROR 2019-01-29 16:09:05,283 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 76, in delete
    query = Image.objects.get(id=pk)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
cvd_portal.models.Image.DoesNotExist: Image matching query does not exist.
ERROR 2019-01-29 16:09:05,285 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17750
ERROR 2019-01-29 16:10:12,689 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 76, in delete
    q = Image.objects.get(id=pk)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
cvd_portal.models.Image.DoesNotExist: Image matching query does not exist.
ERROR 2019-01-29 16:10:12,690 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17746
ERROR 2019-01-29 16:10:21,959 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 76, in delete
    q = Image.objects.get(id=pk).data
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
cvd_portal.models.Image.DoesNotExist: Image matching query does not exist.
ERROR 2019-01-29 16:10:21,960 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17751
ERROR 2019-01-29 16:10:39,646 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 76, in delete
    q = Image.objects.get(id=pk)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
cvd_portal.models.Image.DoesNotExist: Image matching query does not exist.
ERROR 2019-01-29 16:10:39,647 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 17746
ERROR 2019-01-29 16:11:05,283 log Internal Server Error: /sg/api/singleimage/5
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 16:11:05,284 basehttp "DELETE /sg/api/singleimage/5 HTTP/1.1" 500 18071
ERROR 2019-01-29 16:11:38,048 log Internal Server Error: /sg/api/allimages/1
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'PatientAllImagesDetail' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 16:11:38,048 basehttp "DELETE /sg/api/allimages/1 HTTP/1.1" 500 18069
WARNING 2019-01-29 16:12:00,191 log Unauthorized: /sg/api/allimages/1
WARNING 2019-01-29 16:12:00,191 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:12:00,206 log Unauthorized: /sg/api/allimages/1
WARNING 2019-01-29 16:12:00,206 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:12:09,837 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 16:12:09,838 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:12:09,848 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 16:12:09,848 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:12:16,858 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:12:16,858 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 16:12:16,905 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:12:16,906 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 16:12:32,685 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 16:12:34,817 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:12:34,855 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:12:34,984 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:12:44,662 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 367
INFO 2019-01-29 16:13:21,980 basehttp "POST /sg/api/login HTTP/1.1" 200 92
ERROR 2019-01-29 16:13:30,231 log Internal Server Error: /sg/api/allimages/1
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'PatientAllImagesDetail' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 16:13:30,231 basehttp "DELETE /sg/api/allimages/1 HTTP/1.1" 500 18069
ERROR 2019-01-29 16:13:45,817 log Internal Server Error: /sg/api/allimages/1
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'PatientAllImagesDetail' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 16:13:45,817 basehttp "DELETE /sg/api/allimages/1 HTTP/1.1" 500 18069
INFO 2019-01-29 16:13:52,639 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 367
INFO 2019-01-29 16:14:36,322 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
WARNING 2019-01-29 16:14:36,383 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 16:14:36,384 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:14:36,406 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 16:14:36,407 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:14:42,639 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:14:42,640 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 16:14:42,688 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:14:42,689 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 16:14:49,941 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 16:14:52,080 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:14:52,116 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:14:52,237 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:15:14,670 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:15:14,958 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:15:21,905 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:15:22,042 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:15:23,758 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:15:23,866 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:15:25,323 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:15:25,466 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:15:37,723 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:15:37,834 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:15:42,917 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:15:43,035 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:15:43,928 basehttp "POST /sg/api/data HTTP/1.1" 201 338
INFO 2019-01-29 16:15:45,099 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12403
INFO 2019-01-29 16:15:45,228 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:16:57,312 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:16:57,402 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12403
INFO 2019-01-29 16:16:57,766 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:17:02,122 basehttp "DELETE /sg/api/data/46 HTTP/1.1" 204 0
INFO 2019-01-29 16:17:02,187 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:17:02,443 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:17:08,015 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12034
INFO 2019-01-29 16:17:08,147 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:17:08,795 basehttp "POST /sg/api/data HTTP/1.1" 201 338
INFO 2019-01-29 16:19:36,321 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12403
INFO 2019-01-29 16:19:36,524 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:19:47,129 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12403
INFO 2019-01-29 16:19:47,223 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:19:47,885 basehttp "POST /sg/api/data HTTP/1.1" 201 338
INFO 2019-01-29 16:20:53,403 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12772
INFO 2019-01-29 16:20:53,532 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:21:54,095 basehttp "DELETE /sg/api/data/48 HTTP/1.1" 204 0
INFO 2019-01-29 16:21:54,150 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12403
INFO 2019-01-29 16:21:54,503 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:21:58,995 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12403
INFO 2019-01-29 16:21:59,112 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:21:59,756 basehttp "POST /sg/api/data HTTP/1.1" 201 338
INFO 2019-01-29 16:28:55,074 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:28:55,193 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12772
INFO 2019-01-29 16:28:55,524 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:29:01,913 basehttp "POST /sg/api/data HTTP/1.1" 201 338
INFO 2019-01-29 16:29:02,088 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13141
INFO 2019-01-29 16:29:02,279 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:29:09,766 basehttp "DELETE /sg/api/data/50 HTTP/1.1" 204 0
INFO 2019-01-29 16:29:09,834 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12772
INFO 2019-01-29 16:29:10,140 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:29:15,208 basehttp "DELETE /sg/api/data/49 HTTP/1.1" 204 0
INFO 2019-01-29 16:29:15,264 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12403
INFO 2019-01-29 16:29:15,421 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:29:30,287 basehttp "POST /sg/api/data HTTP/1.1" 201 329
INFO 2019-01-29 16:29:30,326 basehttp "POST /sg//api/image HTTP/1.1" 201 5956
INFO 2019-01-29 16:29:30,572 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12838
INFO 2019-01-29 16:29:30,774 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:29:38,923 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
INFO 2019-01-29 16:29:40,736 basehttp "GET /sg/api/singleimage/6 HTTP/1.1" 200 5949
ERROR 2019-01-29 16:29:49,327 log Internal Server Error: /sg/api/singleimage/6
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 16:29:49,327 basehttp "DELETE /sg/api/singleimage/6 HTTP/1.1" 500 17816
INFO 2019-01-29 16:30:04,684 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
INFO 2019-01-29 16:30:10,137 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12838
INFO 2019-01-29 16:30:10,272 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:30:20,303 basehttp "POST /sg/api/login HTTP/1.1" 200 92
INFO 2019-01-29 16:30:29,317 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 456
WARNING 2019-01-29 16:34:21,412 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 16:34:21,413 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:34:21,426 log Unauthorized: /sg/api/patient/1
WARNING 2019-01-29 16:34:21,426 basehttp "GET /sg/api/patient/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:34:30,728 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:34:30,729 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 16:34:30,741 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:34:30,741 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 16:34:40,298 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 16:34:42,390 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:34:42,468 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 12838
INFO 2019-01-29 16:34:42,576 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:34:56,785 basehttp "POST /sg/api/data HTTP/1.1" 201 331
INFO 2019-01-29 16:34:56,838 basehttp "POST /sg//api/image HTTP/1.1" 201 5986
INFO 2019-01-29 16:34:57,023 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13275
INFO 2019-01-29 16:34:57,260 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:35:01,766 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 549
INFO 2019-01-29 16:35:46,104 basehttp "GET /sg/api/singleimage/7 HTTP/1.1" 200 5949
INFO 2019-01-29 16:35:48,010 basehttp "GET /sg/api/singleimage/6 HTTP/1.1" 200 5949
INFO 2019-01-29 16:35:51,409 basehttp "GET /sg/api/singleimage/4 HTTP/1.1" 200 202508
INFO 2019-01-29 16:35:54,296 basehttp "GET /sg/api/singleimage/6 HTTP/1.1" 200 5949
INFO 2019-01-29 16:36:17,156 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 549
ERROR 2019-01-29 16:36:51,985 log Internal Server Error: /sg/api/singleimage/6
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 16:36:51,986 basehttp "DELETE /sg/api/singleimage/6 HTTP/1.1" 500 17816
INFO 2019-01-29 16:37:28,093 basehttp "POST /sg/api/login HTTP/1.1" 200 92
ERROR 2019-01-29 16:37:40,754 log Internal Server Error: /sg/api/singleimage/6
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/mixins.py", line 92, in destroy
    instance = self.get_object()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 85, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
    % self.__class__.__name__
AssertionError: 'ParticularImageByte' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-01-29 16:37:40,755 basehttp "DELETE /sg/api/singleimage/6 HTTP/1.1" 500 18071
ERROR 2019-01-29 16:39:29,778 log Internal Server Error: /sg/api/singleimage/6
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 412, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-01-29 16:39:29,780 basehttp "DELETE /sg/api/singleimage/6 HTTP/1.1" 500 83979
INFO 2019-01-29 16:40:02,507 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 460
ERROR 2019-01-29 16:42:11,127 log Internal Server Error: /sg/api/singleimage/7
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: delete() got an unexpected keyword argument 'pk'
ERROR 2019-01-29 16:42:11,128 basehttp "DELETE /sg/api/singleimage/7 HTTP/1.1" 500 17305
ERROR 2019-01-29 16:42:40,647 log Internal Server Error: /sg/api/singleimage/7
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 412, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-01-29 16:42:40,648 basehttp "DELETE /sg/api/singleimage/7 HTTP/1.1" 500 83979
INFO 2019-01-29 16:42:42,955 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 367
ERROR 2019-01-29 16:42:49,900 log Internal Server Error: /sg/api/singleimage/4
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 412, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-01-29 16:42:49,901 basehttp "DELETE /sg/api/singleimage/4 HTTP/1.1" 500 83979
INFO 2019-01-29 16:42:57,689 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
WARNING 2019-01-29 16:43:06,490 log Unauthorized: /sg/api/allimages/1
WARNING 2019-01-29 16:43:06,491 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:43:06,504 log Unauthorized: /sg/api/allimages/1
WARNING 2019-01-29 16:43:06,505 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:43:09,460 log Unauthorized: /sg/api/allimages/1
WARNING 2019-01-29 16:43:09,460 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:43:09,476 log Unauthorized: /sg/api/allimages/1
WARNING 2019-01-29 16:43:09,477 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 401 27
WARNING 2019-01-29 16:43:15,914 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:43:15,915 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 16:43:15,924 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 16:43:15,924 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 16:43:21,791 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 16:43:23,881 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:43:23,938 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13059
INFO 2019-01-29 16:43:24,031 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:43:27,013 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:43:39,196 basehttp "POST /sg/api/data HTTP/1.1" 201 333
INFO 2019-01-29 16:43:40,028 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13423
INFO 2019-01-29 16:43:40,315 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:43:45,913 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:44:03,821 basehttp "POST /sg/api/data HTTP/1.1" 201 336
INFO 2019-01-29 16:44:03,880 basehttp "POST /sg//api/image HTTP/1.1" 201 5991
INFO 2019-01-29 16:44:04,027 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13863
INFO 2019-01-29 16:44:04,266 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:44:08,504 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 98
INFO 2019-01-29 16:44:11,799 basehttp "GET /sg/api/singleimage/8 HTTP/1.1" 200 5949
ERROR 2019-01-29 16:44:35,953 log Internal Server Error: /sg/api/singleimage/8
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 412, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-01-29 16:44:35,953 basehttp "DELETE /sg/api/singleimage/8 HTTP/1.1" 500 83213
INFO 2019-01-29 16:44:39,334 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:44:45,908 basehttp "DELETE /sg/api/data/54 HTTP/1.1" 204 0
INFO 2019-01-29 16:44:45,961 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13423
INFO 2019-01-29 16:44:46,285 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:44:48,333 basehttp "DELETE /sg/api/data/53 HTTP/1.1" 204 0
INFO 2019-01-29 16:44:48,456 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13059
INFO 2019-01-29 16:44:48,680 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:44:56,792 basehttp "POST /sg/api/data HTTP/1.1" 201 331
INFO 2019-01-29 16:44:57,459 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13421
INFO 2019-01-29 16:44:57,768 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:45:10,723 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:45:24,977 basehttp "POST /sg/api/data HTTP/1.1" 201 330
INFO 2019-01-29 16:45:25,033 basehttp "POST /sg//api/image HTTP/1.1" 201 5986
INFO 2019-01-29 16:45:25,211 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13855
INFO 2019-01-29 16:45:25,432 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:45:35,644 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:45:35,722 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 13855
INFO 2019-01-29 16:45:36,061 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:45:40,888 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 93
ERROR 2019-01-29 16:45:44,363 log Internal Server Error: /sg/api/singleimage/9
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 412, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-01-29 16:45:44,364 basehttp "DELETE /sg/api/singleimage/9 HTTP/1.1" 500 83213
INFO 2019-01-29 16:45:47,667 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:46:45,673 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:46:57,029 basehttp "POST /sg/api/data HTTP/1.1" 201 331
INFO 2019-01-29 16:46:57,085 basehttp "POST /sg//api/image HTTP/1.1" 201 5987
INFO 2019-01-29 16:46:57,287 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14218
INFO 2019-01-29 16:46:57,570 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:47:00,816 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 16:47:15,323 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 16:47:19,657 basehttp "DELETE /sg/api/singleimage/10 HTTP/1.1" 200 17
INFO 2019-01-29 16:47:19,690 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:47:58,079 basehttp "POST /sg/api/data HTTP/1.1" 201 336
INFO 2019-01-29 16:47:58,765 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14511
INFO 2019-01-29 16:47:59,104 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:48:05,080 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 2
INFO 2019-01-29 16:54:39,436 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 16:54:39,532 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14511
INFO 2019-01-29 16:54:39,773 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:55:30,802 basehttp "POST /sg/api/data HTTP/1.1" 201 330
INFO 2019-01-29 16:55:31,487 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14872
INFO 2019-01-29 16:55:31,833 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:55:37,818 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14872
INFO 2019-01-29 16:55:37,974 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:55:45,916 basehttp "DELETE /sg/api/data/59 HTTP/1.1" 204 0
INFO 2019-01-29 16:55:45,975 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14511
INFO 2019-01-29 16:55:46,261 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 16:55:49,186 basehttp "DELETE /sg/api/data/58 HTTP/1.1" 204 0
INFO 2019-01-29 16:55:49,261 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14144
INFO 2019-01-29 16:55:49,507 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:01:19,208 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 17:01:19,290 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14144
INFO 2019-01-29 17:01:19,608 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:01:40,263 basehttp "POST /sg/api/data HTTP/1.1" 201 333
INFO 2019-01-29 17:01:40,362 basehttp "POST /sg//api/image HTTP/1.1" 201 303815
INFO 2019-01-29 17:01:40,507 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14582
INFO 2019-01-29 17:01:40,740 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:01:44,875 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 17:01:46,341 basehttp "GET /sg/api/singleimage/11 HTTP/1.1" 200 303778
INFO 2019-01-29 17:03:42,086 basehttp "GET /sg/api/singleimage/11 HTTP/1.1" 200 303778
INFO 2019-01-29 17:03:42,128 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 17:03:42,206 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14582
INFO 2019-01-29 17:03:42,247 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14582
INFO 2019-01-29 17:03:42,373 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:03:42,429 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:04:05,973 basehttp "POST /sg/api/data HTTP/1.1" 201 332
INFO 2019-01-29 17:04:06,018 basehttp "POST /sg//api/image HTTP/1.1" 201 5988
INFO 2019-01-29 17:04:06,176 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15021
INFO 2019-01-29 17:04:06,389 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:04:09,523 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 189
INFO 2019-01-29 17:04:10,841 basehttp "GET /sg/api/singleimage/12 HTTP/1.1" 200 5950
INFO 2019-01-29 17:04:14,347 basehttp "DELETE /sg/api/singleimage/12 HTTP/1.1" 200 17
INFO 2019-01-29 17:04:14,396 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 17:04:16,562 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 17:04:17,712 basehttp "GET /sg/api/singleimage/11 HTTP/1.1" 200 303778
WARNING 2019-01-29 17:04:26,266 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:04:26,267 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 17:04:26,280 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:04:26,280 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 17:04:33,477 basehttp "POST /sg//api/login HTTP/1.1" 200 91
INFO 2019-01-29 17:04:35,537 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 17:04:35,640 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:04:35,696 basehttp "GET /sg/swasthgarbh/doc/1 HTTP/1.1" 200 4822
INFO 2019-01-29 17:04:45,023 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:04:45,135 basehttp "GET /sg/api/patient/11 HTTP/1.1" 200 475
INFO 2019-01-29 17:04:45,159 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14945
INFO 2019-01-29 17:04:47,727 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14945
INFO 2019-01-29 17:04:57,998 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 17:04:59,472 basehttp "GET /sg/api/singleimage/11 HTTP/1.1" 200 303778
INFO 2019-01-29 17:05:09,416 basehttp "GET /sg/swasthgarbh/patient/1 HTTP/1.1" 200 4297
WARNING 2019-01-29 17:05:28,061 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:05:28,062 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 17:05:28,072 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:05:28,073 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 17:05:34,406 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 17:05:36,491 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 17:05:36,565 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14945
INFO 2019-01-29 17:05:36,664 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:06:57,304 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 17:06:57,390 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14945
INFO 2019-01-29 17:06:57,623 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:07:00,595 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
WARNING 2019-01-29 17:07:06,620 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:07:06,621 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 17:07:06,675 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:07:06,675 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 17:07:12,742 basehttp "POST /sg//api/login HTTP/1.1" 200 91
INFO 2019-01-29 17:07:14,847 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 17:07:14,920 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:07:14,949 basehttp "GET /sg/swasthgarbh/doc/1 HTTP/1.1" 200 4822
INFO 2019-01-29 17:07:16,085 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:07:16,239 basehttp "GET /sg/api/patient/11 HTTP/1.1" 200 475
INFO 2019-01-29 17:07:16,265 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14945
INFO 2019-01-29 17:07:17,533 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14945
INFO 2019-01-29 17:07:19,615 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 17:07:21,608 basehttp "GET /sg/api/singleimage/11 HTTP/1.1" 200 303778
WARNING 2019-01-29 17:07:30,510 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:07:30,510 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-01-29 17:07:30,550 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-01-29 17:07:30,550 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-01-29 17:07:50,591 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-01-29 17:07:52,718 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-01-29 17:07:52,749 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 14945
INFO 2019-01-29 17:07:52,858 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:08:04,877 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 94
INFO 2019-01-29 17:08:06,428 basehttp "GET /sg/api/singleimage/11 HTTP/1.1" 200 303778
INFO 2019-01-29 17:09:08,911 basehttp "POST /sg/api/data HTTP/1.1" 201 329
INFO 2019-01-29 17:09:08,962 basehttp "POST /sg//api/image HTTP/1.1" 201 65023
INFO 2019-01-29 17:09:09,163 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15381
INFO 2019-01-29 17:09:09,451 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 729
INFO 2019-01-29 17:09:12,523 basehttp "GET /sg/api/allimages/1 HTTP/1.1" 200 186
INFO 2019-01-29 17:09:14,390 basehttp "GET /sg/api/singleimage/13 HTTP/1.1" 200 64988
INFO 2019-01-29 17:14:58,596 basehttp "GET /admin/ HTTP/1.1" 200 14310
INFO 2019-01-29 17:14:58,633 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,637 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,637 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,683 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,696 basehttp "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,699 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,702 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,703 basehttp "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,703 basehttp "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2019-01-29 17:14:58,708 basehttp "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,589 basehttp "GET /admin/cvd_portal/patient/ HTTP/1.1" 200 4598
INFO 2019-01-29 17:15:00,634 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,635 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,636 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,639 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,640 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,641 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,642 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,645 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,646 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-01-29 17:15:00,651 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-01-29 17:15:00,726 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2019-02-01 10:26:29,506 basehttp "GET /admin HTTP/1.1" 301 0
INFO 2019-02-01 10:26:29,598 basehttp "GET /admin/ HTTP/1.1" 200 14310
INFO 2019-02-01 10:26:29,689 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:29,690 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:29,690 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:29,701 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:29,755 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:26:29,756 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:26:29,756 basehttp "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:26:29,787 basehttp "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
INFO 2019-02-01 10:26:29,787 basehttp "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
INFO 2019-02-01 10:26:29,791 basehttp "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2019-02-01 10:26:33,452 basehttp "GET /admin/cvd_portal/patient/ HTTP/1.1" 200 4598
INFO 2019-02-01 10:26:33,493 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,494 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,496 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,499 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,501 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,501 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,502 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,505 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,505 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:33,509 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:26:33,613 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2019-02-01 10:26:35,887 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 60073
INFO 2019-02-01 10:26:35,928 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:35,937 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:35,939 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO 2019-02-01 10:26:35,939 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:35,941 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2019-02-01 10:26:35,944 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:26:35,944 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
INFO 2019-02-01 10:26:36,099 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2019-02-01 10:26:36,100 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2019-02-01 10:26:58,040 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 60073
INFO 2019-02-01 10:26:58,075 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,075 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,084 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,084 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,084 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,086 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,090 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,092 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,092 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,096 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:26:58,097 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,119 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,127 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,132 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,132 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,135 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,143 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,163 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,254 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,255 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,300 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:26:58,301 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:27:15,193 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 60216
INFO 2019-02-01 10:27:15,230 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:34:38,805 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 10:34:38,933 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 60270
INFO 2019-02-01 10:34:38,971 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,976 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,980 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,983 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,984 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,988 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,988 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,990 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,995 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:34:38,995 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:38,997 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,015 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,023 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,031 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,035 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,039 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,043 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
INFO 2019-02-01 10:34:39,059 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-02-01 10:34:39,152 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-02-01 10:34:39,153 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2019-02-01 10:34:39,153 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,254 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:34:39,254 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2019-02-01 10:34:50,451 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 10:34:50,543 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 60270
INFO 2019-02-01 10:34:50,627 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:34:54,585 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 10:34:54,682 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 60270
INFO 2019-02-01 10:34:54,776 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:34:54,777 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-02-01 10:34:54,777 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 8192
INFO 2019-02-01 10:34:54,818 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
WARNING 2019-02-01 10:35:52,038 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 10:35:52,039 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-02-01 10:35:52,088 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 10:35:52,089 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-02-01 10:35:59,096 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-02-01 10:36:01,230 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:36:01,316 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:42:03,346 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:42:03,457 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:43:53,551 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:43:53,662 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:45:14,858 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:45:14,968 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:45:44,156 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:45:44,263 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:49:03,815 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:49:03,923 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:49:21,931 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:49:22,050 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
WARNING 2019-02-01 10:49:32,517 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 10:49:32,518 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-02-01 10:49:32,560 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 10:49:32,565 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-02-01 10:49:41,062 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-02-01 10:49:43,173 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:49:43,222 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:49:52,137 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 10:49:52,259 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 61750
INFO 2019-02-01 10:49:52,307 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO 2019-02-01 10:49:52,308 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 8192
INFO 2019-02-01 10:49:52,309 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:49:52,310 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2019-02-01 10:49:52,313 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-02-01 10:49:52,315 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 8192
INFO 2019-02-01 10:49:52,404 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-02-01 10:49:52,456 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2019-02-01 10:50:00,683 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 10:53:47,099 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:53:47,213 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 10:54:51,556 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:54:51,666 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 10:55:55,003 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:55:55,135 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 10:56:05,790 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 10:56:05,901 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 62305
INFO 2019-02-01 10:56:05,948 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 8192
INFO 2019-02-01 10:56:05,952 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:56:05,960 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-02-01 10:56:05,962 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 8192
INFO 2019-02-01 10:56:06,044 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-02-01 10:56:10,603 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:56:18,319 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:56:18,454 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:56:57,158 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:56:57,282 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:57:55,600 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 10:57:55,704 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 10:58:03,606 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 10:58:03,710 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 62860
INFO 2019-02-01 10:58:03,756 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 10:58:07,620 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 10:58:07,745 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 722
INFO 2019-02-01 11:00:45,065 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 11:00:45,179 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 11:00:45,508 basehttp "GET /sg/api/doctor/1 HTTP/1.1" 200 722
INFO 2019-02-01 11:00:51,566 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 11:00:51,682 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 63045
INFO 2019-02-01 11:00:51,731 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:00:51,732 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-02-01 11:00:51,739 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 8192
INFO 2019-02-01 11:00:51,820 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-02-01 11:01:00,234 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 11:01:00,355 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 11:02:03,892 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 11:02:04,018 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 11:02:57,171 basehttp "GET /sg/api/doctor?mobile=1234567890 HTTP/1.1" 200 383
INFO 2019-02-01 11:02:59,009 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 11:02:59,025 basehttp "PUT /sg/api/patient/1 HTTP/1.1" 200 9
INFO 2019-02-01 11:03:01,429 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 11:03:01,542 basehttp "GET /sg/api/doctor/3 HTTP/1.1" 200 614
INFO 2019-02-01 11:03:10,413 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 63192
INFO 2019-02-01 11:03:10,446 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,451 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,456 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,458 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,462 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,462 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,464 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,466 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,469 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,469 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:03:10,471 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,491 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,499 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,507 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,512 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,512 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,515 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,535 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,627 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,629 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,706 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:03:10,713 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:03:14,155 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 11:03:14,251 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 63415
INFO 2019-02-01 11:03:14,336 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:03:21,325 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
WARNING 2019-02-01 11:22:32,971 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 11:22:32,972 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-02-01 11:22:33,013 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 11:22:33,014 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
INFO 2019-02-01 11:22:55,557 basehttp "POST /sg//api/login HTTP/1.1" 200 92
INFO 2019-02-01 11:22:57,682 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 11:22:57,720 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 11:23:02,563 basehttp "GET /sg/swasthgarbh/patient/1 HTTP/1.1" 200 4293
INFO 2019-02-01 11:23:06,046 basehttp "GET /sg/swasthgarbh/patient/1 HTTP/1.1" 200 4293
INFO 2019-02-01 11:23:22,069 basehttp "GET /sg/api/doctor?mobile=1234567890 HTTP/1.1" 200 383
INFO 2019-02-01 11:23:23,668 basehttp "PUT /sg/api/patient/1 HTTP/1.1" 200 9
INFO 2019-02-01 11:23:23,672 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
INFO 2019-02-01 11:23:25,132 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15374
INFO 2019-02-01 11:23:25,239 basehttp "GET /sg/api/doctor/3 HTTP/1.1" 200 614
INFO 2019-02-01 11:24:39,047 basehttp "POST /admin/cvd_portal/patient/1/change/ HTTP/1.1" 302 0
INFO 2019-02-01 11:24:39,142 basehttp "GET /admin/cvd_portal/patient/1/change/ HTTP/1.1" 200 63600
INFO 2019-02-01 11:24:39,184 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2019-02-01 11:24:39,194 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:24:39,194 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 8192
INFO 2019-02-01 11:24:39,194 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO 2019-02-01 11:24:39,199 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-02-01 11:24:39,200 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 8192
INFO 2019-02-01 11:24:39,294 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-02-01 11:24:39,295 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2019-02-01 11:24:42,097 basehttp "GET /sg/api/patient/1 HTTP/1.1" 200 15377
WARNING 2019-02-01 11:24:56,093 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 11:24:56,094 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-02-01 11:24:56,144 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 11:24:56,145 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-02-01 11:30:30,350 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 11:30:30,350 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
WARNING 2019-02-01 11:30:30,394 log Unauthorized: /sg/cbtbiitr/api/device
WARNING 2019-02-01 11:30:30,395 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 401 14
ERROR 2019-02-01 11:35:59,787 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    d = Doctor.objects.get(id=data['doctor'])
KeyError: 'doctor'
ERROR 2019-02-01 11:35:59,788 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17150
ERROR 2019-02-01 11:36:30,279 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:36:30,281 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20351
ERROR 2019-02-01 11:36:35,439 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:36:35,440 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20351
INFO 2019-02-01 11:40:16,748 basehttp "POST /sg/api/login HTTP/1.1" 200 92
ERROR 2019-02-01 11:43:08,825 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:43:08,826 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20592
ERROR 2019-02-01 11:43:27,137 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:43:27,138 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20592
INFO 2019-02-01 11:43:34,424 basehttp "GET /admin/ HTTP/1.1" 200 14731
INFO 2019-02-01 11:43:35,636 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 13365
INFO 2019-02-01 11:43:35,679 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:43:35,726 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2019-02-01 11:43:35,726 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2019-02-01 11:43:35,780 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:43:52,541 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 4241
INFO 2019-02-01 11:43:52,580 basehttp "GET /static/admin/js/cancel.js HTTP/1.1" 304 0
INFO 2019-02-01 11:43:55,389 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:43:55,452 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12223
INFO 2019-02-01 11:43:55,535 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:43:55,574 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:43:55,575 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
ERROR 2019-02-01 11:44:38,035 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    d = Doctor.objects.get(id=data['doctor'])
KeyError: 'doctor'
ERROR 2019-02-01 11:44:38,036 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17391
ERROR 2019-02-01 11:45:09,155 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:45:09,156 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20592
INFO 2019-02-01 11:45:15,006 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:45:15,037 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,038 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,039 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,046 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,047 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,048 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,048 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,049 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,055 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:45:15,056 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,056 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,092 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,092 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,178 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,180 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,180 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,182 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:45:15,183 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:45:22,049 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:45:23,032 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:45:23,100 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:45:23,183 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:45:29,928 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    d = Doctor.objects.get(id=data['doctor'])
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
cvd_portal.models.Doctor.DoesNotExist: Doctor matching query does not exist.
ERROR 2019-02-01 11:45:29,928 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17801
INFO 2019-02-01 11:47:41,437 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:47:41,464 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,472 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,472 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,479 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,479 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,483 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,483 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,484 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,490 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,490 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:47:41,492 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,507 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,523 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,613 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,615 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,617 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,617 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:47:41,618 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:47:45,235 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:47:46,142 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:47:46,208 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:47:46,287 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:47:49,269 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 251, in post
    d = null
NameError: name 'null' is not defined
ERROR 2019-02-01 11:47:49,270 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17400
INFO 2019-02-01 11:49:21,057 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:49:21,093 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,096 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,104 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,104 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,105 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,110 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,110 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,111 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,113 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,118 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:49:21,119 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,135 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,147 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,239 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,240 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,240 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,241 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:21,245 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:26,145 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:49:27,194 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:49:27,263 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:49:27,337 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:49:30,840 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 200 75
INFO 2019-02-01 11:49:38,361 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:49:38,401 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,401 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,401 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,402 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,404 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,407 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,407 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,409 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,412 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,415 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:49:38,417 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,443 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,451 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,545 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,546 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,546 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,546 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:38,547 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:49:42,205 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3813
INFO 2019-02-01 11:49:43,603 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:49:43,660 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:49:43,736 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:49:50,743 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    if(data['doctor']):
KeyError: 'doctor'
ERROR 2019-02-01 11:49:50,745 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17128
ERROR 2019-02-01 11:49:59,204 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:49:59,206 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20351
ERROR 2019-02-01 11:50:11,682 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:50:11,682 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20592
INFO 2019-02-01 11:50:17,064 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:50:17,102 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,104 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,105 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,106 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,107 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,109 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,111 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,111 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,112 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,117 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:50:17,119 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,143 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,151 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,239 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,243 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,243 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,245 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:17,246 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:21,616 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:50:22,409 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:50:22,499 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:50:22,576 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:50:27,282 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    if(data['doctor']):
KeyError: 'doctor'
ERROR 2019-02-01 11:50:27,282 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17369
INFO 2019-02-01 11:50:55,454 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:50:55,492 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,494 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,494 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,495 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,495 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,503 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,504 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,505 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,506 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,508 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:50:55,509 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,535 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,543 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,631 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,632 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,635 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,639 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:55,639 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:50:59,105 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:50:59,903 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:50:59,966 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:51:00,047 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:51:16,883 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    if(data['doctor']):
KeyError: 'doctor'
ERROR 2019-02-01 11:51:16,884 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17128
ERROR 2019-02-01 11:51:40,326 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 245, in post
    u.save()
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
ERROR 2019-02-01 11:51:40,327 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 20592
INFO 2019-02-01 11:51:43,823 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:51:43,859 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,860 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,862 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,862 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,864 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,865 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,870 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,871 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,871 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,875 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:51:43,877 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,903 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,907 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:51:43,999 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:51:44,001 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:51:44,002 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:51:44,002 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:51:44,003 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:51:47,066 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:51:48,078 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:51:48,144 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:51:48,219 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:51:51,126 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    if(data['doctor']):
KeyError: 'doctor'
ERROR 2019-02-01 11:51:51,127 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17369
INFO 2019-02-01 11:52:12,693 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:52:12,727 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,729 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,729 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,729 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,729 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,736 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,737 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,737 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,739 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:52:12,740 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,741 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,771 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,779 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,867 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,867 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,870 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,876 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:12,876 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:16,072 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:52:17,017 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:52:17,081 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:52:17,156 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:52:19,879 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 248, in post
    if(data['doctor']):
KeyError: 'doctor'
ERROR 2019-02-01 11:52:19,880 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17369
INFO 2019-02-01 11:52:36,103 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:52:36,139 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,141 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,142 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,142 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,143 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,143 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,148 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,150 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,151 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:52:36,152 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,153 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,183 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,187 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,279 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,280 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,281 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,282 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:36,282 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:52:39,505 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:52:40,588 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:52:40,654 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:52:40,736 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
ERROR 2019-02-01 11:52:48,303 log Internal Server Error: /sg/api/onboard/patient
Traceback (most recent call last):
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sahil/swasthGarbh/sgenv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sahil/swasthGarbh/sgBackend/cvd_portal/views.py", line 271, in post
    email=data['email'],
KeyError: 'email'
ERROR 2019-02-01 11:52:48,304 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 500 17376
INFO 2019-02-01 11:53:16,527 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:53:16,583 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12702
INFO 2019-02-01 11:53:16,655 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:53:16,698 basehttp "GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504
INFO 2019-02-01 11:53:19,534 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:53:19,570 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,572 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,572 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,573 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,573 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,574 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,577 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,578 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,582 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,584 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:53:19,586 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,616 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,616 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,700 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,700 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,701 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,708 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:19,708 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:22,764 basehttp "POST /admin/auth/user/ HTTP/1.1" 200 3344
INFO 2019-02-01 11:53:23,695 basehttp "POST /admin/auth/user/ HTTP/1.1" 302 0
INFO 2019-02-01 11:53:23,763 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12222
INFO 2019-02-01 11:53:23,846 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:53:31,977 basehttp "POST /sg/api/onboard/patient HTTP/1.1" 200 75
INFO 2019-02-01 11:53:34,098 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 11:53:34,116 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
INFO 2019-02-01 11:53:41,993 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:53:42,025 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,026 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,027 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,027 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,028 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,029 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,029 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,035 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,036 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,039 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:53:42,040 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,072 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,072 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,158 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,159 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,160 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,161 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:42,163 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2019-02-01 11:53:45,902 basehttp "GET /admin/auth/user/34/change/ HTTP/1.1" 200 21508
INFO 2019-02-01 11:53:45,940 basehttp "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 5755
INFO 2019-02-01 11:53:45,940 basehttp "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12712
INFO 2019-02-01 11:53:45,946 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:53:45,949 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2019-02-01 11:53:46,015 basehttp "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2019-02-01 11:53:46,015 basehttp "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2019-02-01 11:53:46,016 basehttp "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2019-02-01 11:53:51,030 basehttp "GET /admin/auth/user/ HTTP/1.1" 200 12523
INFO 2019-02-01 11:54:04,713 basehttp "GET /sg/api/doctor?mobile=1234567890 HTTP/1.1" 200 383
INFO 2019-02-01 11:54:05,966 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
INFO 2019-02-01 11:54:06,001 basehttp "PUT /sg/api/patient/13 HTTP/1.1" 200 10
INFO 2019-02-01 11:54:07,497 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 649
INFO 2019-02-01 11:54:07,626 basehttp "GET /sg/api/doctor/3 HTTP/1.1" 200 613
INFO 2019-02-01 11:57:36,219 basehttp "GET /admin/ HTTP/1.1" 200 14236
INFO 2019-02-01 11:57:37,909 basehttp "GET /admin/cvd_portal/patient/ HTTP/1.1" 200 4601
INFO 2019-02-01 11:57:37,943 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:57:39,167 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63493
INFO 2019-02-01 11:57:39,208 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:57:44,950 basehttp "POST /admin/cvd_portal/patient/13/change/ HTTP/1.1" 302 0
INFO 2019-02-01 11:57:45,046 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63714
INFO 2019-02-01 11:57:45,126 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 11:57:48,092 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
INFO 2019-02-01 11:58:12,006 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
INFO 2019-02-01 11:58:20,938 basehttp "GET /sg/api/doctor?mobile=1234567890 HTTP/1.1" 200 383
INFO 2019-02-01 11:58:23,300 basehttp "PUT /sg/api/patient/13 HTTP/1.1" 200 10
INFO 2019-02-01 12:01:18,261 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 649
INFO 2019-02-01 12:01:18,403 basehttp "GET /sg/api/doctor/3 HTTP/1.1" 200 613
INFO 2019-02-01 12:01:22,897 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63493
INFO 2019-02-01 12:01:22,932 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,935 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,940 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,942 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,943 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,943 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,947 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,950 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,950 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,955 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 12:01:22,957 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,971 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,983 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,992 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,992 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,995 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2019-02-01 12:01:22,999 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 12:01:23,015 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2019-02-01 12:01:23,104 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:01:23,105 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:01:23,164 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:01:23,164 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:01:25,871 basehttp "POST /admin/cvd_portal/patient/13/change/ HTTP/1.1" 302 0
INFO 2019-02-01 12:01:25,969 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63714
INFO 2019-02-01 12:01:26,051 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 12:01:28,477 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
INFO 2019-02-01 12:01:36,465 basehttp "GET /sg/api/doctor?mobile=1234567890 HTTP/1.1" 200 383
INFO 2019-02-01 12:01:37,692 basehttp "PUT /sg/api/patient/13 HTTP/1.1" 200 10
INFO 2019-02-01 12:01:40,564 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 649
INFO 2019-02-01 12:01:40,655 basehttp "GET /sg/api/doctor/3 HTTP/1.1" 200 613
INFO 2019-02-01 12:02:17,760 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 649
INFO 2019-02-01 12:02:17,864 basehttp "GET /sg/api/doctor/3 HTTP/1.1" 200 613
INFO 2019-02-01 12:02:21,173 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63493
INFO 2019-02-01 12:02:21,203 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,203 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,213 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,214 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,214 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,214 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,215 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,221 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,222 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,224 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,227 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 12:02:21,255 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,259 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,264 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,264 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,267 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,271 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,299 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,391 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,391 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,463 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:02:21,463 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:02:23,751 basehttp "POST /admin/cvd_portal/patient/13/change/ HTTP/1.1" 302 0
INFO 2019-02-01 12:02:23,846 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63714
INFO 2019-02-01 12:02:23,932 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 12:02:26,195 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
INFO 2019-02-01 12:02:48,962 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 12:02:49,084 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
INFO 2019-02-01 12:02:56,653 basehttp "GET /sg/api/doctor?mobile=1234567890 HTTP/1.1" 200 383
INFO 2019-02-01 12:02:57,821 basehttp "PUT /sg/api/patient/13 HTTP/1.1" 200 10
INFO 2019-02-01 12:02:57,881 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 649
INFO 2019-02-01 12:02:57,950 basehttp "GET /sg/api/doctor/3 HTTP/1.1" 200 613
INFO 2019-02-01 12:03:16,380 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63678
INFO 2019-02-01 12:03:16,421 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,421 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,422 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,424 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,425 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,429 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,431 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,433 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,434 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,436 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 12:03:16,438 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,463 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,471 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,476 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,476 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,479 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,483 basehttp "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,507 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,598 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,598 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,648 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:03:16,648 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
INFO 2019-02-01 12:03:19,626 basehttp "POST /admin/cvd_portal/patient/13/change/ HTTP/1.1" 302 0
INFO 2019-02-01 12:03:19,725 basehttp "GET /admin/cvd_portal/patient/13/change/ HTTP/1.1" 200 63899
INFO 2019-02-01 12:03:19,807 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-02-01 12:04:56,497 basehttp "POST /sg/cbtbiitr/api/device HTTP/1.1" 200 11
INFO 2019-02-01 12:04:56,589 basehttp "GET /sg/api/patient/13 HTTP/1.1" 200 652
